# Comprehensive Sector Map for Top NSE & BSE Stocks
SECTOR_MAP = {
    "IT": [
        "TCS.NS", "INFY.NS", "WIPRO.NS", "HCLTECH.NS", "TECHM.NS", "LTIM.NS", "PERSISTENT.NS", "COFORGE.NS", "TATAELXSI.NS",
        "KPITTECH.NS", "LTTS.NS", "BSOFT.NS", "CYIENT.NS", "MPHASIS.NS", "ZENSARTECH.NS", "SONATSOFTW.NS", "OFSS.NS", "MASTEK.NS",
        "500209.BO", "532281.BO", "532174.BO"
    ],
    "AUTO": [
        "TATAMOTORS.NS", "M&M.NS", "MARUTI.NS", "BAJAJ-AUTO.NS", "EICHERMOT.NS", "TVSMOTOR.NS", "HEROMOTOCO.NS", "ASHOKLEY.NS",
        "BHARATFORG.NS", "BALKRISIND.NS", "MRF.NS", "APOLLOTYRE.NS", "SONACOMS.NS", "ESCORTS.NS", "TUBACEREAL.NS", "EXIDEIND.NS",
        "500520.BO", "500182.BO"
    ],
    "BANK": [
        "HDFCBANK.NS", "ICICIBANK.NS", "SBIN.NS", "AXISBANK.NS", "KOTAKBANK.NS", "INDUSINDBK.NS", "BANKBARODA.NS", "CANBK.NS",
        "IDFCFIRSTB.NS", "PNB.NS", "FEDERALBNK.NS", "AUBANK.NS", "BANDHANBNK.NS", "IDBI.NS", "YESBANK.NS", "CENTRALBK.NS",
        "500180.BO", "532134.BO"
    ],
    "PHARMA": [
        "SUNPHARMA.NS", "CIPLA.NS", "DRREDDY.NS", "DIVISLAB.NS", "LUPIN.NS", "AUROPHARMA.NS", "TORNTPHARM.NS", "BIOCON.NS",
        "ALKEM.NS", "ABBOTT.NS", "MANKIND.NS", "ZYDUSLIFE.NS", "GLENMARK.NS", "IPCALAB.NS", "LAURUSLABS.NS", "PFIZER.NS",
        "500124.BO", "500087.BO"
    ],
    "ENERGY": [
        "RELIANCE.NS", "ONGC.NS", "NTPC.NS", "POWERGRID.NS", "COALINDIA.NS", "BPCL.NS", "IOC.NS", "GAIL.NS", "TATAPOWER.NS",
        "ADANIGREEN.NS", "ADANIPOWER.NS", "GUJGASLTD.NS", "IGL.NS", "MGL.NS", "PETRONET.NS", "SJVN.NS", "NHPC.NS",
        "500325.BO", "532555.BO"
    ],
    "FINANCE": [
        "LICI.NS", "BAJFINANCE.NS", "BAJAJFINSV.NS", "HDFCLIFE.NS", "SBILIFE.NS", "CHOLAFIN.NS", "RECLTD.NS", "PFC.NS",
        "MUTHOOTFIN.NS", "SHREERAMFIN.NS", "M&MFIN.NS", "POONAWALLA.NS", "BAJAJHLDNG.NS", "HUDCO.NS", "GICRE.NS",
        "500034.BO", "532978.BO"
    ],
    "METAL": [
        "TATASTEEL.NS", "JSWSTEEL.NS", "HINDALCO.NS", "VEDL.NS", "JINDALSTEL.NS", "NATIONALUM.NS", "SAIL.NS", "NMDC.NS",
        "APOLLOPIP.NS", "HINDZINC.NS", "RATNAMANI.NS", "WELCORP.NS", "JSL.NS", "500440.BO", "500228.BO"
    ],
    "CONSUMER": [
        "ITC.NS", "HINDUNILVR.NS", "NESTLEIND.NS", "BRITANNIA.NS", "TATACONSUM.NS", "VBL.NS", "GODREJCP.NS", "DABUR.NS",
        "COLPAL.NS", "MARICO.NS", "BERGEPAINT.NS", "ASIANPAINT.NS", "TITAN.NS", "TRENT.NS", "PIDILITIND.NS", "PAGEIND.NS",
        "500875.BO", "500820.BO"
    ],
    "INFRA": [
        "LT.NS", "ADANIENT.NS", "ADANIPORTS.NS", "SIEMENS.NS", "ABB.NS", "CUMMINSIND.NS", "BEL.NS", "HAL.NS", "BHEL.NS",
        "IRCTC.NS", "CONCOR.NS", "RVNL.NS", "IRCON.NS", "MAZDOCK.NS", "GRSE.NS", "500510.BO"
    ],
    "REALTY": [
        "DLF.NS", "LODHA.NS", "GODREJPROP.NS", "OBEROIRLTY.NS", "PHOENIXLTD.NS", "PRESTIGE.NS", "BRIGADE.NS", "SOBHA.NS", "SUNTECK.NS"
    ]
}

def get_sector(symbol):
    for sector, symbols in SECTOR_MAP.items():
        if symbol in symbols: return sector
    return "OTHERS"
