# Comprehensive Sector Map for NSE/BSE Top Stocks
SECTOR_MAP = {
    "IT": ["TCS.NS", "INFY.NS", "WIPRO.NS", "HCLTECH.NS", "TECHM.NS", "LTIM.NS", "PERSISTENT.NS", "COFORGE.NS", "TATAELXSI.NS", "KPITTECH.NS", "LTTS.NS", "BSOFT.NS", "CYIENT.NS", "MPHASIS.NS"],
    "AUTO": ["TATAMOTORS.NS", "M&M.NS", "MARUTI.NS", "BAJAJ-AUTO.NS", "EICHERMOT.NS", "TVSMOTOR.NS", "HEROMOTOCO.NS", "ASHOKLEY.NS", "BHARATFORG.NS", "BALKRISIND.NS", "MRF.NS", "APOLLOTYRE.NS", "SONACOMS.NS"],
    "BANK": ["HDFCBANK.NS", "ICICIBANK.NS", "SBIN.NS", "AXISBANK.NS", "KOTAKBANK.NS", "INDUSINDBK.NS", "BANKBARODA.NS", "CANBK.NS", "IDFCFIRSTB.NS", "PNB.NS", "FEDERALBNK.NS", "AU SMALL FINANCE.NS", "BANDHANBNK.NS"],
    "PHARMA": ["SUNPHARMA.NS", "CIPLA.NS", "DRREDDY.NS", "DIVISLAB.NS", "LUPIN.NS", "AUROPHARMA.NS", "TORNTPHARM.NS", "BIOCON.NS", "ALKEM.NS", "ABBOTT.NS", "MANKIND.NS", "ZYDUSLIFE.NS", "GLENMARK.NS"],
    "ENERGY": ["RELIANCE.NS", "ONGC.NS", "NTPC.NS", "POWERGRID.NS", "COALINDIA.NS", "BPCL.NS", "IOC.NS", "GAIL.NS", "TATAPOWER.NS", "ADANIGREEN.NS", "ADANIPOWER.NS", "GUJGASLTD.NS", "IGL.NS"],
    "FINANCE": ["LICI.NS", "BAJFINANCE.NS", "BAJAJFINSV.NS", "HDFCLIFE.NS", "SBILIFE.NS", "CHOLAFIN.NS", "RECLTD.NS", "PFC.NS", "MUTHOOTFIN.NS", "SHREERAMFIN.NS", "M&MFIN.NS", "POONAWALLA.NS"],
    "METAL": ["TATASTEEL.NS", "JSWSTEEL.NS", "HINDALCO.NS", "VEDL.NS", "JINDALSTEL.NS", "NATIONALUM.NS", "SAIL.NS", "NMDC.NS", "APOLLOPIP.NS", "HINDZINC.NS"],
    "CONSUMER": ["ITC.NS", "HINDUNILVR.NS", "NESTLEIND.NS", "BRITANNIA.NS", "TATACONSUM.NS", "VBL.NS", "GODREJCP.NS", "DABUR.NS", "COLPAL.NS", "MARICO.NS", "BERGEPAINT.NS", "ASIANPAINT.NS"],
    "REALTY": ["DLF.NS", "LODHA.NS", "GODREJPROP.NS", "OBEROIRLTY.NS", "PHOENIXLTD.NS", "PRESTIGE.NS", "BRIGADE.NS"],
    "BSE_TOP": ["500325.BO", "500209.BO", "532174.BO", "500180.BO", "500182.BO", "500696.BO", "532215.BO"] # Reliance, Infosys, ICICI, etc on BSE
}

def get_sector(symbol):
    for sector, symbols in SECTOR_MAP.items():
        if symbol in symbols: return sector
    return "OTHERS"
